# SQL script to create database and tables
# Database name: call_detail_records
# CDR Table Name: cdr
# CMR Table Name: cmr

delimiter $$

CREATE DATABASE IF NOT EXISTS `call_detail_records` /*!40100 DEFAULT CHARACTER SET latin1 */$$
USE `call_detail_records`$$

CREATE TABLE IF NOT EXISTS `cdr` (
  `cdrRecordType` int(10) NOT NULL,
  `globalCallID_callManagerId` int(10) NOT NULL,
  `globalCallID_callId` int(10) NOT NULL,
  `origLegCallIdentifier` int(10) DEFAULT NULL,
  `dateTimeOrigination` int(10) DEFAULT NULL,
  `origNodeId` int(10) DEFAULT NULL,
  `origSpan` int(10) DEFAULT NULL,
  `origIpAddr` int(10) DEFAULT NULL,
  `callingPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `callingPartyUnicodeLoginUserID` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `origCause_location` int(10) DEFAULT NULL,
  `origCause_value` int(10) DEFAULT NULL,
  `origPrecedenceLevel` int(10) DEFAULT NULL,
  `origMediaTransportAddress_IP` int(10) DEFAULT NULL,
  `origMediaTransportAddress_Port` int(10) DEFAULT NULL,
  `origMediaCap_payloadCapability` int(10) DEFAULT NULL,
  `origMediaCap_maxFramesPerPacket` int(10) DEFAULT NULL,
  `origMediaCap_g723BitRate` int(10) DEFAULT NULL,
  `origVideoCap_Codec` int(10) DEFAULT NULL,
  `origVideoCap_Bandwidth` int(10) DEFAULT NULL,
  `origVideoCap_Resolution` int(10) DEFAULT NULL,
  `origVideoTransportAddress_IP` int(10) DEFAULT NULL,
  `origVideoTransportAddress_Port` int(10) DEFAULT NULL,
  `origRSVPAudioStat` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `origRSVPVideoStat` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `destLegIdentifier` int(10) DEFAULT NULL,
  `destNodeId` int(10) DEFAULT NULL,
  `destSpan` int(10) DEFAULT NULL,
  `destIpAddr` int(10) DEFAULT NULL,
  `originalCalledPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `finalCalledPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `finalCalledPartyUnicodeLoginUserID` varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  `destCause_location` int(10) DEFAULT NULL,
  `destCause_value` int(10) DEFAULT NULL,
  `destPrecedenceLevel` int(10) DEFAULT NULL,
  `destMediaTransportAddress_IP` int(10) DEFAULT NULL,
  `destMediaTransportAddress_Port` int(10) DEFAULT NULL,
  `destMediaCap_payloadCapability` int(10) DEFAULT NULL,
  `destMediaCap_maxFramesPerPacket` int(10) DEFAULT NULL,
  `destMediaCap_g723BitRate` int(10) DEFAULT NULL,
  `destVideoCap_Codec` int(10) DEFAULT NULL,
  `destVideoCap_Bandwidth` int(10) DEFAULT NULL,
  `destVideoCap_Resolution` int(10) DEFAULT NULL,
  `destVideoTransportAddress_IP` int(10) DEFAULT NULL,
  `destVideoTransportAddress_Port` int(10) DEFAULT NULL,
  `destRSVPAudioStat` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `destRSVPVideoStat` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `dateTimeConnect` int(10) DEFAULT NULL,
  `dateTimeDisconnect` int(10) DEFAULT NULL,
  `lastRedirectDn` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `pkid` varchar(64) CHARACTER SET latin1 NOT NULL,
  `originalCalledPartyNumberPartition` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `callingPartyNumberPartition` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `finalCalledPartyNumberPartition` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `lastRedirectDnPartition` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `duration` int(10) DEFAULT NULL,
  `origDeviceName` varchar(129) CHARACTER SET latin1 DEFAULT NULL,
  `destDeviceName` varchar(129) CHARACTER SET latin1 DEFAULT NULL,
  `origCallTerminationOnBehalfOf` int(10) NOT NULL,
  `destCallTerminationOnBehalfOf` int(10) NOT NULL,
  `origCalledPartyRedirectOnBehalfOf` int(10) NOT NULL,
  `lastRedirectRedirectOnBehalfOf` int(10) NOT NULL,
  `origCalledPartyRedirectReason` int(10) DEFAULT NULL,
  `lastRedirectRedirectReason` int(10) DEFAULT NULL,
  `destConversationId` int(10) DEFAULT NULL,
  `globalCallId_ClusterID` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `joinOnBehalfOf` int(10) NOT NULL,
  `comment` varchar(2048) CHARACTER SET latin1 DEFAULT NULL,
  `authCodeDescription` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `authorizationLevel` int(10) DEFAULT NULL,
  `clientMatterCode` varchar(16) CHARACTER SET latin1 DEFAULT NULL,
  `origDTMFMethod` int(10) DEFAULT NULL,
  `destDTMFMethod` int(10) DEFAULT NULL,
  `callSecuredStatus` int(10) DEFAULT NULL,
  `origConversationId` int(10) DEFAULT NULL,
  `origMediaCap_Bandwidth` int(10) DEFAULT NULL,
  `destMediaCap_Bandwidth` int(10) DEFAULT NULL,
  `authorizationCodeValue` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `outpulsedCallingPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `outpulsedCalledPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `origIpv4v6Addr` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `destIpv4v6Addr` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `origVideoCap_Codec_Channel2` int(10) DEFAULT NULL,
  `origVideoCap_Bandwidth_Channel2` int(10) DEFAULT NULL,
  `origVideoCap_Resolution_Channel2` int(10) DEFAULT NULL,
  `origVideoTransportAddress_IP_Channel2` int(10) DEFAULT NULL,
  `origVideoTransportAddress_Port_Channel2` int(10) DEFAULT NULL,
  `origVideoChannel_Role_Channel2` int(10) DEFAULT NULL,
  `destVideoCap_Codec_Channel2` int(10) DEFAULT NULL,
  `destVideoCap_Bandwidth_Channel2` int(10) DEFAULT NULL,
  `destVideoCap_Resolution_Channel2` int(10) DEFAULT NULL,
  `destVideoTransportAddress_IP_Channel2` int(10) DEFAULT NULL,
  `destVideoTransportAddress_Port_Channel2` int(10) DEFAULT NULL,
  `destVideoChannel_Role_Channel2` int(10) DEFAULT NULL,
  `IncomingProtocolID` int(10) DEFAULT NULL,
  `IncomingProtocolCallRef` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `OutgoingProtocolID` int(10) DEFAULT NULL,
  `OutgoingProtocolCallRef` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `currentRoutingReason` int(10) DEFAULT NULL,
  `origRoutingReason` int(10) DEFAULT NULL,
  `lastRedirectingRoutingReason` int(10) DEFAULT NULL,
  `huntPilotPartition` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `huntPilotDN` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `calledPartyPatternUsage` int(10) DEFAULT NULL,
  `IncomingICID` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `IncomingOrigIOI` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `IncomingTermIOI` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `OutgoingICID` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `OutgoingOrigIOI` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `OutgoingTermIOI` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `outpulsedOriginalCalledPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `outpulsedLastRedirectingNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `wasCallQueued` int(10) DEFAULT '0',
  `totalWaitTimeInQueue` int(10) DEFAULT '0',
  `callingPartyNumber_uri` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `originalCalledPartyNumber_uri` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `finalCalledPartyNumber_uri` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `lastRedirectDn_uri` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `mobileCallingPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `finalMobileCalledPartyNumber` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `origMobileDeviceName` varchar(129) CHARACTER SET latin1 DEFAULT NULL,
  `destMobileDeviceName` varchar(129) CHARACTER SET latin1 DEFAULT NULL,
  `origMobileCallDuration` int(10) DEFAULT '0',
  `destMobileCallDuration` int(10) DEFAULT '0',
  `mobileCallType` int(10) DEFAULT '0',
  `originalCalledPartyPattern` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `finalCalledPartyPattern` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `lastRedirectingPartyPattern` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `huntPilotPattern` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`pkid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE IF NOT EXISTS `cmr` (
  `cdrRecordType` int(1) DEFAULT NULL,
  `globalCallID_callManagerId` int(1) DEFAULT NULL,
  `globalCallID_callId` int(6) DEFAULT NULL,
  `nodeId` int(1) DEFAULT NULL,
  `directoryNum` varchar(50) DEFAULT NULL,
  `callIdentifier` int(8) DEFAULT NULL,
  `dateTimeStamp` int(10) DEFAULT NULL,
  `numberPacketsSent` int(3) DEFAULT NULL,
  `numberOctetsSent` int(5) DEFAULT NULL,
  `numberPacketsReceived` int(3) DEFAULT NULL,
  `numberOctetsReceived` int(5) DEFAULT NULL,
  `numberPacketsLost` int(1) DEFAULT NULL,
  `jitter` int(1) DEFAULT NULL,
  `latency` int(1) DEFAULT NULL,
  `pkid` varchar(64) NOT NULL,
  `directoryNumPartition` varchar(50) DEFAULT NULL,
  `globalCallId_ClusterID` varchar(50) DEFAULT NULL,
  `deviceName` varchar(129) DEFAULT NULL,
  `varVQMetrics` varchar(600) DEFAULT NULL,
  `duration` int(10) DEFAULT '0',
  `videoContentType` varchar(10) DEFAULT NULL,
  `videoDuration` int(11) DEFAULT '0',
  `numberVideoPacketsSent` int(11) DEFAULT NULL,
  `numberVideoOctetsSent` int(11) DEFAULT NULL,
  `numberVideoPacketsReceived` int(11) DEFAULT NULL,
  `numberVideoOctetsReceived` int(11) DEFAULT NULL,
  `numberVideoPacketsLost` int(11) DEFAULT NULL,
  `videoAverageJitter` int(11) DEFAULT NULL,
  `videoRoundTripTime` int(11) DEFAULT NULL,
  `videoOneWayDelay` int(11) DEFAULT NULL,
  `videoReceptionMetrics` varchar(600) DEFAULT NULL,
  `videoTransmissionMetrics` varchar(600) DEFAULT NULL,
  `videoContentType_channel2` varchar(10) DEFAULT NULL,
  `videoDuration_channel2` int(11) DEFAULT NULL,
  `numberVideoPacketsSent_channel2` int(11) DEFAULT NULL,
  `numberVideoOctetsSent_channel2` int(11) DEFAULT NULL,
  `numberVideoPacketsReceived_channel2` int(11) DEFAULT NULL,
  `numberVideoOctetsReceived_channel2` int(11) DEFAULT NULL,
  `numberVideoPacketsLost_channel2` int(11) DEFAULT NULL,
  `videoAverageJitter_channel2` int(11) DEFAULT NULL,
  `videoRoundTripTime_channel2` int(11) DEFAULT NULL,
  `videoOneWayDelay_channel2` int(11) DEFAULT NULL,
  `videoReceptionMetrics_channel2` varchar(600) DEFAULT NULL,
  `videoTransmissionMetrics_channel2` varchar(600) DEFAULT NULL,
  PRIMARY KEY (`pkid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$
